[package]
name = "y-dash"
version.workspace = true
authors.workspace = true
edition.workspace = true
homepage.workspace = true
documentation.workspace = true
repository.workspace = true
license.workspace = true
description = "A yrs server by viz"
keywords = ["yrs", "viz"]
